name: docker

on:
  # Run every morning at 4:18am to automatically stay up to date
  schedule:
    - cron: "18 4 * * *"
  # Run when any of the build setup changes
  push:
    branches: [master]
    paths-ignore:
      - '**/**.md'
      - '.gitignore'
  # Also allow manual runs
  workflow_dispatch:

env:
  IMAGE_NAME: "portalknights-server"
  BUILD_IMAGE: "true"
  BUILD_ID: "none"

jobs:
  build-image:
    name: Build Portal Knights dedicated server Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get current build ID for Portal Knights
        run: |
          BUILD_ID=$(curl https://api.steamcmd.net/v1/info/374040 \
          | jq '.data."374040".depots.branches.public.buildid' \
          | sed s/\"//g) \
          && echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV

      - name: Check whether ${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }} exists
        run: |
          IMAGE_TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}/tags | jq -r ".[].name") || IMAGE_TAGS="none"
          for tag in ${IMAGE_TAGS[@]}; do
            if [[ "$tag" == " ${{ env.BUILD_ID }}" ]]; then
              echo "BUILD_IMAGE=false" >> $GITHUB_ENV
              exit
            fi
          done

      - uses: actions/checkout@v2
        if: ${{ env.BUILD_IMAGE == 'true' }}
        name: Check out code

      - name: Generate datestamp
        if: ${{ env.BUILD_IMAGE == 'true' }}
        run: |
          DATESTAMP=$(date +%Y-%m-%d)
          echo "DATESTAMP=${DATESTAMP}" >> $GITHUB_ENV

      - name: Generate Docker image metadata
        if: ${{ env.BUILD_IMAGE == 'true' }}
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,${{ env.BUILD_ID }}
            type=raw,{{ date YYYY-MM-DD }}
            type=raw,latest

      - name: Setup Docker BuildKit
        if: ${{ env.BUILD_IMAGE == 'true' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ env.BUILD_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.BUILD_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push ${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }} Docker image
        if: ${{ env.BUILD_IMAGE == 'true' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            STEAM_USERNAME=${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD=${{ secrets.STEAM_PASSWORD }}
          file: Dockerfile
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
